name: ansiparser
description: A convenient library for converting ANSI escape sequences into text or HTML.
version: 1.0.0
repository: https://github.com/bubble-tea-project/ansiparser-dart

environment:
  sdk: ^3.5.2

dependencies:
  html: ^0.15.4
  collection: ^1.19.1
  east_asian_width: ^1.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
